<script>
    async function getResponse() {
        try {
            let res =  await new Promise((resolve, reject) => {
                reject("Resolve")
            })
            console.log(res);
        } catch (err) {
            console.log(err);
        }
    }

    getResponse();
</script>